version: '3'

services:
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:RV770xtx@localhost:5432/Coffeeboog?schema=public
    ports:
      - '3000:3000'
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=RV770xtx
      - POSTGRES_DB=Coffeeboog
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
